BASIC NUMPY ARRAYS

In [3]:
import sys
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, 0.5, 1, 1.5, 2])

In [6]:
a[1], a[2]

(np.int64(2), np.int64(3))

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
a[[0, 2, -1]]

array([1, 3, 4])

ARRAY DATA TYPES

In [12]:
a

array([1, 2, 3, 4])

In [13]:
a.dtype

dtype('int64')

In [14]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
b.dtype

dtype('float64')

In [16]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [17]:
c = np.array(['a','b','c'])

In [18]:
c.dtype

dtype('<U1')

In [19]:
d = np.array([{'a':1}, sys])

In [20]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

In [21]:
d.dtype

dtype('O')

DIMENSIONS AND SHAPES

In [22]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

In [23]:
A.shape

(2, 3)

In [24]:
A.ndim

2

In [25]:
A.size

6

In [26]:
B = np.array([[[1, 2, 3],
              [4, 5, 6]
              ],
              [[7, 8, 9],
               [10, 11, 12]
               ]])

In [27]:
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
B.shape

(2, 2, 3)

In [29]:
B.ndim

3

In [30]:
B.size

12

INDEXING AND SLICING OF MATRICES

In [31]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [32]:
A[1]

array([4, 5, 6])

In [33]:
A[1, 0]

np.int64(4)

In [34]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [36]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [37]:
A[:2, 2:]

array([[3],
       [6]])

In [38]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
A[1] = np.array([10, 11, 12])

In [40]:
A

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 7,  8,  9]])

In [41]:
A[2] = 99

In [42]:
A

array([[ 1,  2,  3],
       [10, 11, 12],
       [99, 99, 99]])

In [ ]:
...