BASIC NUMPY ARRAYS

In [1]:
import sys
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
b = np.array([0, 0.5, 1, 1.5, 2])

In [4]:
a[1], a[2]

(np.int64(2), np.int64(3))

In [5]:
a[0:]

array([1, 2, 3, 4])

In [6]:
a[1:3]

array([2, 3])

In [7]:
a[1:-1]

array([2, 3])

In [8]:
a[::2]

array([1, 3])

In [9]:
a[[0, 2, -1]]

array([1, 3, 4])

ARRAY DATA TYPES

In [10]:
a

array([1, 2, 3, 4])

In [11]:
a.dtype

dtype('int64')

In [12]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [13]:
b.dtype

dtype('float64')

In [14]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [15]:
c = np.array(['a','b','c'])

In [16]:
c.dtype

dtype('<U1')

In [17]:
d = np.array([{'a':1}, sys])

In [18]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

In [19]:
d.dtype

dtype('O')

DIMENSIONS AND SHAPES

In [20]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

In [21]:
A.shape

(2, 3)

In [22]:
A.ndim

2

In [23]:
A.size

6

In [24]:
B = np.array([[[1, 2, 3],
              [4, 5, 6]
              ],
              [[7, 8, 9],
               [10, 11, 12]
               ]])

In [25]:
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
B.shape

(2, 2, 3)

In [27]:
B.ndim

3

In [28]:
B.size

12

INDEXING AND SLICING OF MATRICES

In [29]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [30]:
A[1]

array([4, 5, 6])

In [31]:
A[1, 0]

np.int64(4)

In [32]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [34]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [35]:
A[:2, 2:]

array([[3],
       [6]])

In [36]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
A[1] = np.array([10, 11, 12])

In [38]:
A

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 7,  8,  9]])

In [39]:
A[2] = 99

In [40]:
A

array([[ 1,  2,  3],
       [10, 11, 12],
       [99, 99, 99]])

SUMMARY STATISTICS

In [41]:
a = np.array([1, 2, 3, 4])

In [42]:
a.sum()

np.int64(10)

In [43]:
a.mean()

np.float64(2.5)

In [44]:
a.std()

np.float64(1.118033988749895)

In [45]:
a.var()

np.float64(1.25)

In [46]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [47]:
A.sum()

np.int64(45)

In [48]:
A.mean()

np.float64(5.0)

In [49]:
A.std()

np.float64(2.581988897471611)

In [50]:
A.sum(axis=0)

array([12, 15, 18])

In [51]:
A.sum(axis=1)

array([ 6, 15, 24])

In [52]:
A.mean(axis=0)

array([4., 5., 6.])

In [53]:
A.mean(axis=1)

array([2., 5., 8.])

In [54]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [55]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

BROADCASTING AND VECTORIZED OPERATION

In [56]:
a = np.arange(4)

In [57]:
a

array([0, 1, 2, 3])

In [58]:
a + 10

array([10, 11, 12, 13])

In [59]:
a * 10

array([ 0, 10, 20, 30])

In [60]:
a

array([0, 1, 2, 3])

In [61]:
a += 100

In [62]:
a

array([100, 101, 102, 103])

In [65]:
l = [0, 1, 2, 3]
[i * 10 for i in l]

[0, 10, 20, 30]

In [66]:
a = np.arange(4)

In [67]:
a

array([0, 1, 2, 3])

In [68]:
b = np.array([10, 10, 10, 10])

In [69]:
b

array([10, 10, 10, 10])

In [70]:
a + b

array([10, 11, 12, 13])

In [71]:
a * b

array([ 0, 10, 20, 30])